create database easySched;
CREATE TABLE `Billing Address` (ID int(10) NOT NULL AUTO_INCREMENT, CompanyID int(10) NOT NULL, Street varchar(255), `Postal Code : String` int(10), City varchar(255), Province varchar(255), PRIMARY KEY (ID));
CREATE TABLE Company (ID int(10) NOT NULL AUTO_INCREMENT, Name varchar(255), CompanyNumber varchar(255), PRIMARY KEY (ID));
CREATE TABLE Employee (ID int(10) NOT NULL AUTO_INCREMENT, PrivelegesID int(10) NOT NULL, CompanyID int(10) NOT NULL, `FirstName : String` int(10), `LastName : String` int(10), `EmployeeNumber : String` int(10), `Email : String` int(10), Wages double, PRIMARY KEY (ID));
CREATE TABLE `Employee Availability` (ID int(10) NOT NULL AUTO_INCREMENT, WeekdayID int(10) NOT NULL, EmployeeID int(10) NOT NULL, `Start : TimeSpan` int(10), `End : TimeSpan` int(10), PRIMARY KEY (ID));
CREATE TABLE `Employee Schedule` (ID int(10) NOT NULL AUTO_INCREMENT, EmployeeID int(10) NOT NULL, `Start` double NOT NULL, `End` double NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Licencing (ID int(10) NOT NULL AUTO_INCREMENT, CompanyID int(10) NOT NULL, Cost double, `Start : TimeSpan` int(10), `End` int(10), PRIMARY KEY (ID));
CREATE TABLE Phone (ID int(10) NOT NULL AUTO_INCREMENT, CompanyID int(10) NOT NULL, EmployeeID int(10), PhoneTypeID int(10) NOT NULL, Number int(10) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE PhoneType (ID int(10) NOT NULL AUTO_INCREMENT, Type varchar(255), PRIMARY KEY (ID));
CREATE TABLE Priveleges (ID int(10) NOT NULL AUTO_INCREMENT, Type int(10), PRIMARY KEY (ID));
CREATE TABLE Weekday (ID int(10) NOT NULL AUTO_INCREMENT, Day int(10), PRIMARY KEY (ID));
ALTER TABLE `Employee Schedule` ADD CONSTRAINT `FKEmployee S183223` FOREIGN KEY (EmployeeID) REFERENCES Employee (ID);
ALTER TABLE Phone ADD CONSTRAINT FKPhone530938 FOREIGN KEY (PhoneTypeID) REFERENCES PhoneType (ID);
ALTER TABLE Employee ADD CONSTRAINT FKEmployee833112 FOREIGN KEY (PrivelegesID) REFERENCES Priveleges (ID);
ALTER TABLE Licencing ADD CONSTRAINT FKLicencing37786 FOREIGN KEY (CompanyID) REFERENCES Company (ID);
ALTER TABLE Phone ADD CONSTRAINT FKPhone588853 FOREIGN KEY (CompanyID) REFERENCES Company (ID);
ALTER TABLE Phone ADD CONSTRAINT FKPhone263678 FOREIGN KEY (EmployeeID) REFERENCES Employee (ID);
ALTER TABLE Employee ADD CONSTRAINT FKEmployee435943 FOREIGN KEY (CompanyID) REFERENCES Company (ID);
ALTER TABLE `Employee Availability` ADD CONSTRAINT `FKEmployee A593831` FOREIGN KEY (WeekdayID) REFERENCES Weekday (ID);
ALTER TABLE `Employee Availability` ADD CONSTRAINT `FKEmployee A983524` FOREIGN KEY (EmployeeID) REFERENCES Employee (ID);
ALTER TABLE `Billing Address` ADD CONSTRAINT `FKBilling Ad812261` FOREIGN KEY (CompanyID) REFERENCES Company (ID);
